package streams

// Message unit of transport containing data issued by the system and metadata used by `streams` internal
// mechanisms. This unit will be/is transported through one or more streams.
type Message struct {
	// Name of the stream this Message will be/is transported.
	StreamName string `json:"stream_name"`
	// Type of Data content.
	//
	// The usage of the RFC2046 MIME specification is preferred (e.g. application/json, application/xml).
	//
	// Reference: https://www.rfc-editor.org/rfc/rfc2046.
	ContentType string `json:"content_type"`
	// Encoded data generated by the system transported in a specific stream.
	Data []byte `json:"data"`
}
