version: '3.8'
services:
  postgres:
    image: postgres:13-alpine3.17
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTRGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample_database
    volumes:
      - ./thirdparty/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./thirdparty/scripts/sample_database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./thirdparty/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./thirdparty/scripts/kafka_update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"

  egress-proxy:
    image: ghcr.io/alexandria-oss/egress-proxy-log-listener-agent:0.0.1-alpha.1
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    env_file:
      - deployments/env.list
