version: '3.8'
services:
  dynamodb-go:
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-go
    ports:
      - '8000:8000'
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
